name: test

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'feature/*'
      - 'releases/*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    name: '[PHP] Check coding style'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-cache-node-modules

      - name: Install dependencies
        run: npm install

      - name: Test template
        run: |
          moleculer init --answers test/ci/answers.json --install . ci-test
          cd ci-test
          npm i
          npm run lint
          npm run test